baseURL = "https://pko89403.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "pko89403"
title = "유기농은 너무 비싸서 그런데 농약 친 건 어딨나요?"
theme = "vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["AI","BE","ML"]

	# Add meta description in head part
	description = "I'm working as backend developer. M.S. from PNU CSE. I'm interested in recommederI'm working as backend developer. M.S. from PNU CSE. I'm interested in recommeder"

	# Add pagetitle to homepage <title> tag
	pagetitle = "All about static site generation"

	# Add a subtitle to your website
	subtitle = "[]()"

	# Activate to show authors on pages if available
	#listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "/img/Avatar.png"

	# Optional favicons for website
	favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = true

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
shortname = "Slave" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
host = "Master" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/pko89403"

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
cmd = "mailto:pko89403@gmail.com"

#[[params.social]]
#name = "RSS"
#icon = "fas fa-rss"
#url = "/index.xml"